if (A_Language = "0804")
{
    global _Author="知阳"
    global _Exit="退出 Power Keys"
    global _Restart="重启 Power Keys"
    global _Updating="正在更新 Power Keys"
    global _EnableSpace="启用空格编辑【Caps Lock + Space】"
    global _DisableSpace="禁用空格编辑【Caps Lock + Space】"
    global _EnableGameMode="启用游戏模式【Win + Esc】"
    global _DisableGameMode="禁用游戏模式【Win + Esc】"
    global _StartUp="开机自启"
    global _Config="配置快捷键【F1 ~ F12 + Enter】"
    global _Help="帮助文档【Win + F1】"
    global _Feedback="反馈与建议"
    global _Update="更新 Power Keys"
    global _ConfirmEmptyRecycleBin="确定清空回收站？"
    global _Require64="请使用 64 位版本。"
    global _SpaceEnabled="空格编辑已启用"
    global _SpaceDisabled="空格编辑已禁用"
    global _GameModeEnabled="游戏模式已启用"
    global _GameModeDisabled="游戏模式已禁用"
    global _PoorNetwork="与 GitHub 连接不畅！请稍后再试。"
    global _PressWinKey="请按徽标键"
}
else
{
    global _Author="szzhiyang"
    global _Exit="Quit Power Keys"
    global _Restart="Restart Power Keys"
    global _Update="Update Power Keys"
    global _Updating="Updating Power Keys"
    global _EnableSpace="Enable Power Space【Caps Lock + Space】"
    global _DisableSpace="Disable Power Space【Caps Lock + Space】"
    global _EnableGameMode="Enable Game Mode【Win + Esc】"
    global _DisableGameMode="Disable Game Mode【Win + Esc】"
    global _StartUp="Run At Startup"
    global _Config="Configure Hotkeys【F1 ~ F12 + Enter】"
    global _Help="Help File【Win + F1】"
    global _Feedback="Feedback and Request"
    global _ConfirmEmptyRecycleBin="Clear recycle bin?"
    global _Require64="Please use the 64-bit version."
    global _SpaceEnabled="Power Space Enabled"
    global _SpaceDisabled="Power Space Disabled"
    global _GameModeEnabled="Game Mode Enabled"
    global _GameModeDisabled="Game Mode Disabled"
    global _PoorNetwork="Poor connection with GitHub! Please try again later."
    global _PressWinKey="Please press Windows Key"
}